### ISSUE TITLE
Plugin into Pybullet

### ISSUE THREAD

**Issue by shivanimall** [MAPIRlab/gaden#20]
Hello,

Do you have a plugin into PyBullet? (I saw one for Unity)

Thank you!

**Comment by PepeOjeda** [comment]
Hello. 
I am afraid no such integration exists, at least for now. However, it seems like there already exist projects for bridging pyBullet and ROS (for example, [this one](https://github.com/oscar-lima/pybullet_ros)) , so it should be possible to use the existing ROS implementation. 

I cannot confirm the viability of this approach, however, since I am not familiar with PyBullet.
