### ISSUE TITLE
get_parameter_or error

### ISSUE THREAD

**Issue by lvzhoujing** [MAPIRlab/gaden#37]
error: no matching function for call to ‘Environment::get_parameter_or<std::string>(const char*, const char [1])’
  227 |         CAD_models[i] = get_parameter_or<std::string>(paramName.c_str(), "");

**Comment by PepeOjeda** [comment]
This is a surprising error, because `get_parameter_or` is a `rclcpp::Node` member function, not something we have defined. Which version of ROS are you using?

**Comment by lvzhoujing** [comment]
> This is a surprising error, because `get_parameter_or` is a `rclcpp::Node` member function, not something we have defined. Which version of ROS are you using?

Thanks for your reply! I'm using ROS2 foxy, and I'm trying changing to ROS2 humble right now.

**Comment by PepeOjeda** [comment]
Humble is the version that we are using for developement (and is an LTS version), so that's probably a good idea. 
I'm looking at the foxy headers, and it seems like [that specific version](https://github.com/ros2/rclcpp/blob/humble/rclcpp/include/rclcpp/node_impl.hpp#L318) of `get_parameter_or` (the one that returns the parameter value, rather than a boolean) [did not exist](https://github.com/ros2/rclcpp/blob/foxy/rclcpp/include/rclcpp/node_impl.hpp#L242) back then, so changing to humble should fix the problem.

I'll add something to the readme about Humble being the officially supported version to avoid this sort of problem in the future.
