### ISSUE TITLE
MOX sensor readings

### ISSUE THREAD

**Issue by jbourne15** [MAPIRlab/gaden#4]
I was wondering if you could explain the response of the simulated MOX sensors specifically, why does the concentration (in ppm) go down when the sensors are within the emitting filaments?

![screenshot from 2017-08-17 14-54-02](https://user-images.githubusercontent.com/10954148/29433413-437d99c8-835c-11e7-86c2-80d23ac6c99c.png)

**Comment by JGMonroy** [comment]
Hi jbourne15,
I think the misunderstanding is that the sensors are providing readings in [Ohm] not in [ppm], therefore when the gas concentration increases, the sensor resistance decreases, as seen in your plot. That is, GADEN provides measures in [ppm], but when you simulate a MOX sensor you obtain the sensor readings based on the concentration they are exposed to. For the case of MOX sensors (you can see the manufacturer's datasheets) the readings are based on the sensor resistance changes, therefore the value you obtain by simulating a MOX sensor is the sensor resistance (Ohms).

If you want to see what is the concentration in (ppm), you can simulate a PID sensor, which provides measurements in (ppm) rather than resistances.

**Comment by jbourne15** [comment]
Thank you for this clarification, I was under the impression that the simulated MOX sensors reported ppm.
