### ISSUE TITLE
about CoppeliaSimulator --auto-start option

### ISSUE THREAD

**Issue by 8ijuu** [MAPIRlab/gaden#41]
Hello
After compiling Gaden, I first ran ros2 launch test_env gaden_preproc_launch.py. In the CoppeliaSimulator, it displayed the error "the argument ('/home/gouqin/Gaden_ws/install/coppelia_ros2_pkg/share/coppelia_ros2_pkg/scenes/ros2_mapirlab_pioneer.ttt') for option '--auto-start' is invalid". I suspect the parameter '/home/gouqin/Gaden_ws/install/coppelia_ros2_pkg/share/coppelia_ros2_pkg/scenes/ros2_mapirlab_pioneer.ttt' was incorrectly assigned to the '--auto-start' option, but I can't find this option in the launch file.
![image](https://github.com/MAPIRlab/gaden/assets/52631053/f9e8e2ac-ee7c-4048-a37a-ac5d57246810)

**Comment by PepeOjeda** [comment]
I'm afraid I cannot reproduce this problem. Try downloading the most recent version of the [utils](https://github.com/MAPIRlab/utils) repository, as I have modified the coppelia_ros2_pkg node so that it logs to the terminal the complete command that it is using to run coppelia. Looking at that might give more insight into what is going wrong here.

**Comment by 8ijuu** [comment]
Hello！I solved the problem by reinstalling the virtual machine and downloading CoppeliaSim 4.5.0. Thank you.
