### ISSUE TITLE
invalid quaternions

### ISSUE THREAD

**Issue by r-miko** [MAPIRlab/gaden#7]
Hello,

When I run the launch file gaden_simulator_demo.launch I get this error:

![screenshot from 2018-01-17 10-45-43](https://user-images.githubusercontent.com/32842219/35038835-ecab8f8e-fb73-11e7-8340-37ce7b4fc73b.png)

Have I missed something?

Thanks in advance,
Rebecca

**Comment by JGMonroy** [comment]
Hi r-miko,
Is this problem related to the solved [issue 8](https://github.com/MAPIRlab/gaden/issues/8)??.
If not, the problem is related to the visualization of some markers on rviz (the gas sources) which are defined in the node "environment". They do not affect the simulation, but I'll take a look after the latest commits if the problem persists.

**Comment by r-miko** [comment]
Hello Javier,

It must have been related to #8 as the problem is now gone. 
Thanks again!
